# This is a basic CodeMagic workflow for a Flutter iOS project.
# For more advanced configurations, refer to the CodeMagic documentation:
# https://docs.codemagic.io/yaml/building-flutter-apps/

workflows:
  ios-build:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "Runner"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    scripts:
      - name: Flutter clean
        script: |
          flutter clean

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Build iOS (Release)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $CM_BUILD_DIR/ios/${APP_NAME}.xcarchive

    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true