# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'ios', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.read(generated_xcode_build_settings_path).strip.match(/FLUTTER_ROOT=(.*)/)[1]
end

require_relative File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
